### ISSUE TITLE
학습량에 대해서

### ISSUE THREAD

**Issue by h1a2l1o5** [sce-tts/sce-tts.github.io#5]
안녕하세요!!
이런 엄청난 코드 공개해주셔서 감사합니다!

제가 이번에 4시간정도의 데이터셋을 녹음해서 제대로된 tts를 만들려고하는데요

코랩에는 얼만큼 학습시켜야하는지에 대해선 안나와있네요...

혹시 pre-train된 모델은 얼만큼 학습시키셨고 배치사이즈는 어떻게 되는지
학습에 사용된 파라미터를 알 수 있을까요?

**Comment by rishubil** [comment]
본 프로젝트에서 제공하는 사전 학습 모델은 구글 코랩을 통하여 학습을 진행하지 않았습니다.
따라서 코랩에서 실제로 학습을 진행하는데 얼마나 걸릴지는 저도 아직 정확히 알기 어렵습니다.
(누군가 다른 분이 구글 코랩으로 실제로 진행한 결과를 공유해주시기를 막연히 기다리고 있습니다...)

사전 학습 과정은 RTX 6000을 사용하였으며, Glow-TTS는 약 2.5일간 학습을 진행했습니다.
MB-MelGAN은 지금 로그가 유실되어 정확히 학습에 소요된 시간은 알 수 없으나, Glow-TTS와 비슷한 시간이었던걸로 기억합니다.

아래는 사전 학습 모델을 배포할 때 기록했던 TensorBoard의 스크린샷입니다.
총 학습 Step을 참고하여 코랩을 통한 학습의 예상 소요 시간을 추론해보실 수 있을겁니다.

Glow-TTS
![glowtts_scalars](https://user-images.githubusercontent.com/382014/93459215-58a79680-f91c-11ea-95b2-f6d9aa60a0ca.png)

MB-MelGAN
![mb_melgan_train](https://user-images.githubusercontent.com/382014/93459210-56ddd300-f91c-11ea-8c8c-948fd7f1a7d5.png)

---

배치 사이즈와 파라미터는 공유한 Repo에 있는 설정 값을 그대로 사용하고 있습니다.
아래 두 파일을 참고해주세요.

https://github.com/sce-tts/glow-tts/blob/master/configs/base.json
https://github.com/sce-tts/TensorflowTTS/blob/r0.7/examples/multiband_melgan/conf/multiband_melgan.v1.yaml

**Comment by h1a2l1o5** [comment]
2.5일 정도 걸리는군요... 듣기로는 코랩 지속시간이 12시간이라고 하던데 아무래도 다른방안을 찾아봐야 할것같네요 ㅠㅠ 

그래도 답변 감사합니다!

**Comment by rishubil** [comment]
저는 정보통신산업진흥원의 인공지능 고성능 컴퓨팅 자원 지원 사업을 이용하여 학습을 진행했습니다.
신청 절차가 필요하지만, 일반 개발자도 무료로 이용할 수 있습니다.

자세한 내용은 아래 링크들을 참조해보세요.

https://somjang.tistory.com/entry/%EB%B9%84%EC%8B%BC-GPU-%EC%A7%80%EC%9B%90-%EB%B0%9B%EC%95%84-%EB%AC%B4%EB%A3%8C%EB%A1%9C-%EC%82%AC%EC%9A%A9%ED%95%B4%EB%B3%B4%EC%9E%90-Ai-Hub-GPU-%EC%8B%A0%EC%B2%AD-%EB%B0%A9%EB%B2%95
https://aihub.or.kr/node/223

**Comment by h1a2l1o5** [comment]
오 저런 사업도 있군요...

일단 저는 aws의 p3인스턴스를 할당해서 학습을 하려하는데요.

glow-tts학습이 한 iteration에 대략 1초~2초 정도 걸리는데 혹시 35k학습이 맞을까요 ㅠㅠ
이정도면 하루정도면 학습이 전부 끝날것같아서 제가 본게 맞나 싶어서요...

아! 그리고 대본은 딱히 어떤걸 사용해도 상관없을까요...
아니면 저 대본은 어떤 원리로 구성하셨나요?

**Comment by rishubil** [comment]
> glow-tts학습이 한 iteration에 대략 1초~2초 정도 걸리는데 혹시 35k학습이 맞을까요 ㅠㅠ
이정도면 하루정도면 학습이 전부 끝날것같아서 제가 본게 맞나 싶어서요...

저도 머신러닝 관련 경험이 별로 없어서, 확답을 드리기는 조금 어렵습니다 :sweat_smile:

> 아! 그리고 대본은 딱히 어떤걸 사용해도 상관없을까요...
아니면 저 대본은 어떤 원리로 구성하셨나요?

음성 녹음 과정에서 사용하는 한국어 코퍼스는 한국정보화진흥원 AI Hub에서 제공하는 한국어 대화 텍스트 데이터와 한국어-영어 번역(병렬) 말뭉치 텍스트 데이터를 사용했습니다.
(해당 내용은 https://sce-tts.github.io/#/license 에서 확인하실 수 있습니다.)

**Comment by h1a2l1o5** [comment]
그렇군요... 학습 관련해서는 몇번 돌려보면서 경험을 해봐야할것같네요...

답변 감사합니다!
